name = "DragonRealm Unofficial"
author = "ReikaKaleski"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d9188808246b3c9175528e77a88d8fcc9502acd1b73ba01c06fcc10674487d2f"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
unsup = "1.2.0-pre1"
