name = "DragonRealm Unofficial"
author = "ReikaKaleski"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "859dd9c996daa2f2f81575940540c08ddae4709cd878607d62e4fe8255c46e58"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
unsup = "1.2.0-pre1"
