name = "DragonRealm Unofficial"
author = "ReikaKaleski"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "80cf049e3682acc2b7ecd010a13e65f8d13ec4316e79a10509b1c05c95f0f1be"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
unsup = "1.0.1"
