[flavor_groups.betterfoliage]
name = "Better Foliage"
description = "Adds bushy leaves, grassy grass blocks, falling leaf particles, algae and more. Highly configurable, anything can be disabled. Client only."
side = "client"
[[flavor_groups.betterfoliage.choices]]
id = "betterfoliage_on"
name = "Yes"
description = "Installs Better Foliage."
[[flavor_groups.betterfoliage.choices]]
id = "betterfoliage_off"
name = "No"
description = "Do not install Better Foliage."

[flavor_groups.chameleoncreepers]
name = "Chameleon Creepers"
description = "Shifts the hue of creepers to match their surroundings, giving them camouflage like they originally had. Client only."
side = "client"
[[flavor_groups.chameleoncreepers.choices]]
id = "chameleoncreepers_on"
name = "Yes"
description = "Installs Chameleon Creepers."
[[flavor_groups.chameleoncreepers.choices]]
id = "chameleoncreepers_off"
name = "No"
description = "Do not install Chameleon Creepers."

# This is technically not optional in upstream DragonRealm...
[flavor_groups.dualhotbar]
name = "Dual Hotbar"
description = "Makes the top row of your inventory (can be changed) into a fully functional extra hotbar, by default on top of your normal hotbar (9 columns, two rows), but can be configured into an 18-slot long hotbar. Client grants partial functionality (hotbar slot swapping), if on server as well then full functionality."
side = "both"
[[flavor_groups.dualhotbar.choices]]
id = "dualhotbar_on"
name = "Yes"
description = "Installs Dual Hotbar."
[[flavor_groups.dualhotbar.choices]]
id = "dualhotbar_off"
name = "No"
description = "Do not install Dual Hotbar."

[flavor_groups.dynamicsurroundings]
name = "Dynamic Surroundings"
description = "Adds various sounds based on what you are doing and what is happening around and to you as well as an aurora in the sky at night. Can also be used to block out *any* sound. Client only."
side = "client"
[[flavor_groups.dynamicsurroundings.choices]]
id = "dynamicsurroundings_on"
name = "Yes"
description = "Installs Dynamic Surroundings."
[[flavor_groups.dynamicsurroundings.choices]]
id = "dynamicsurroundings_off"
name = "No"
description = "Do not install Dynamic Surroundings."

[flavor_groups.ears]
name = "Ears"
description = "Uses the otherwise-blank space on a modern 64x64 skin in combination with alpha layer encoding to give extra features to your player model, such as ears, wings, a custom cape, breasts, a snout and more. Client only. No effect (other than seeing other players Ears skins) if you do not have an Ears skin. Client only."
side = "client"
[[flavor_groups.ears.choices]]
id = "ears_on"
name = "Yes"
description = "Installs Ears."
[[flavor_groups.ears.choices]]
id = "ears_off"
name = "No"
description = "Do not install Ears."

# It *is* an officially supported configuration, after all...
# Not by me it isn't.
[flavor_groups.optifine]
name = "OptiFine"
description = "Install Optifine?."
side = "client"
[[flavor_groups.optifine.choices]]
id = "no"
name = "No"
description = "Does not install Optifine."
[[flavor_groups.optifine.choices]]
id = "godsno"
name = "Hell no"
description = "Does not install Optifine, why are you even asking this?"

[flavor_groups.soundfilters]
name = "Sound Filters"
description = "Adds reverb to caves and underwater/covered up muting. Client only."
side = "client"
[[flavor_groups.soundfilters.choices]]
id = "soundfilters_on"
name = "Yes"
description = "Installs Sound Filters."
[[flavor_groups.soundfilters.choices]]
id = "soundfilters_off"
name = "No"
description = "Do not install Sound Filters."

[flavor_groups.voxelmap]
name = "VoxelMap"
description = "Provides a mini/world map. May cause issues on macOS. Client only.\nEnabling either this or WorldEdit CUI will also install LiteLoader."
side = "client"
[[flavor_groups.voxelmap.choices]]
id = "voxelmap_on"
name = "Yes"
description = "Installs Voxelmap."
[[flavor_groups.voxelmap.choices]]
id = "voxelmap_off"
name = "No"
description = "Do not install VoxelMap."

[flavor_groups.worldeditcui]
name = "WorldEdit CUI"
description = "Shows your WorldEdit selection. Client only.\nEnabling either this or VoxelMap will also install LiteLoader."
side = "client"
[[flavor_groups.worldeditcui.choices]]
id = "worldeditcui_on"
name = "Yes"
description = "Installs WorldEdit CUI."
[[flavor_groups.worldeditcui.choices]]
id = "worldeditcui_off"
name = "No"
description = "Do not install WorldEdit CUI."

[flavor_groups.tyksera]
name = "Tyksera"
description = "Reika's 1.7.10 resourcepack made from a mixture of vanilla textures, custom textures and recombinated textures from other packs such as Faithful 32x, Sphax and Adventure Island. Only downloads Tyksera, does not enable it. It can also be found at https://dragonrealm.overminddl1.com/texture.php for later installs."
side = "client"
[[flavor_groups.tyksera.choices]]
id = "tyksera_on"
name = "Yes"
description = "Downloads Tyksera."
[[flavor_groups.tyksera.choices]]
id = "tyksera_off"
name = "No"
description = "Do not download Tyksera."

[metafile.better-foliage]
flavors = "betterfoliage_on"
[metafile.chameleoncreepers]
flavors = "chameleoncreepers_on"
[metafile.dual-hotbar]
flavors = "dualhotbar_on"
[metafile.dynamic-surroundings]
flavors = "dynamicsurroundings_on"
[metafile.ears]
flavors = "ears_on"
[metafile.liteloader]
flavors = ["voxelmap_on", "worldeditcui_on"]
[metafile.sound-filters]
flavors = "soundfilters_on"
[metafile.voxelmap-litemod]
flavors = "voxelmap_on"
[metafile.worldeditcui-litemod]
flavors = "worldeditcui_on"
[metafile.tyksera]
flavors = "tyksera_on"